import type { Metadata } from "next";
import {Ubuntu_Sans} from "next/font/google";
import "./globals.css";

const ubuntuSans = Ubuntu_Sans({
    variable: "--font-ubuntu-sans",
    subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuSans.variable}`}
      >
      <div className={`bg-stone-900 min-h-screen p-6 text-lime-100/80`}>
        {children}
      </div>
      </body>
    </html>
  );
}
